### ISSUE TITLE
Enable SSE for S3 Buckets

### ISSUE THREAD

**Issue by martijnvdgrift** [dnvriend/sbt-sam#102]
Currently, SBT-SAM supports Server Side Encryption (SSE) for AWS Kinesis and AWS DynamoDB. We should add this for AWS S3 Buckets as well.

**Comment by martijnvdgrift** [comment]
Error while implementing this feature:
`"A conflicting conditional operation is currently in progress against this resource. Please try again."
"The following resource(s) failed to create: [SbtSamDeploymentBucket]. . Rollback requested by user."`

According to AWS Support, there is an open bug for this CloudFormation issue.

**Comment by dnvriend** [comment]
I tried to deploy a bucket with SSE enabled and it seems to work now. I have merged the necessary changes to the code and the next release v1.0.28 will have SSE enabled buckets.

**Comment by martijnvdgrift** [comment]
nice!
