### ISSUE TITLE
Add support for SNS events

### ISSUE THREAD

**Issue by martijnvdgrift** [dnvriend/sbt-sam#22]
Add support for the [SNS](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#sns) event type. This means adding a new Lambda annotation, i.e.: @SNSHandler, new Lambda type SNSHandler, creating the necessary changes in sbt-sam sbt plugin to detect and add the Lambda type to the list of Lambdas and create a new CloudFormation block to set the event type for the Lambda.

**Comment by dnvriend** [comment]
I've added the lambda and JSON event parser, but there is no annotation, SNSConf, and cloudformation event definition yet.
