### ISSUE TITLE
Add support for Kinesis events

### ISSUE THREAD

**Issue by martijnvdgrift** [dnvriend/sbt-sam#23]
Add support for the [Kinesis](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#kinesis) event type. This means adding a new Lambda annotation, i.e.: @KinesisHandler, new Lambda type KinesisHandler, creating the necessary changes in sbt-sam sbt plugin to detect and add the Lambda type to the list of Lambdas and create a new CloudFormation block to set the event type for the Lambda.

**Comment by dnvriend** [comment]
I've added the lambda and JSON event parser, but there is no annotation, KinesisConf, and cloudformation event definition yet.
