### ISSUE TITLE
samInfo always shows kinesis stream status as not deployed

### ISSUE THREAD

**Issue by kkessels** [dnvriend/sbt-sam#85]
When you deploy, for example, the data-segment seed it deploys properly as confirmed when checking cloudformation, however samInfo always shows the kinesis stream as "not yet deployed" even though it is there and operational. SamInfo does show the correct information for the role, firehose, and bucket.

**Comment by dnvriend** [comment]
You should add the following setting to your .sbtopts `-Dcom.amazonaws.sdk.disableCbor` for example, a full file contents would be:

```
-J-Xms512m
-J-Xmx1024m
-J-XX:MaxMetaspaceSize=1024m
-J-XX:-UseConcMarkSweepGC
-J-XX:+UseG1GC
-J-XX:MaxGCPauseMillis=200
-Dcom.amazonaws.sdk.disableCbor
```
